package com.pojo;
// Generated Feb 28, 2018 5:42:38 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Tour generated by hbm2java
 */
@Entity
@XmlRootElement
public class Tour implements java.io.Serializable {

    @Id
    @GeneratedValue

    private Integer id;
    private String fname;
    private String lname;
    private String email;
    private String phone;
    private String country;
    private String dist;
    private String person;
    private String vehicle;
    private String comment;
   
    
    public Tour() {
    }

    public Tour(String fname, String lname, String email, String phone, String country, String dist, String person, String vehicle, String comment) {
        this.fname = fname;
        this.lname = lname;
        this.email = email;
        this.phone = phone;
        this.country = country;
        this.dist = dist;
        this.person = person;
        this.vehicle = vehicle;
        this.comment = comment;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFname() {
        return this.fname;
    }

    public void setFname(String fname) {
        this.fname = fname;
    }

    public String getLname() {
        return this.lname;
    }

    public void setLname(String lname) {
        this.lname = lname;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getDist() {
        return this.dist;
    }

    public void setDist(String dist) {
        this.dist = dist;
    }

    public String getPerson() {
        return this.person;
    }

    public void setPerson(String person) {
        this.person = person;
    }

    public String getVehicle() {
        return this.vehicle;
    }

    public void setVehicle(String vehicle) {
        this.vehicle = vehicle;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
}